extends Control
const UI = preload("res://scripts/card_ui.gd")
func _ready() -> void:
	theme = UI.theme()
	var background := ColorRect.new(); background.color = Color("0b1b24")
	background.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT); add_child(background)
	var center := CenterContainer.new(); center.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT); add_child(center)
	var panel := PanelContainer.new(); panel.custom_minimum_size = Vector2(760,0)
	panel.add_theme_stylebox_override("panel",UI.style(Color("132f37"),24)); center.add_child(panel)
	var col := VBoxContainer.new(); col.add_theme_constant_override("separation",18); panel.add_child(col)
	col.add_child(UI.label("CARD ROOM   /   纸牌会客厅",34,Color("f4e7bf")))
	col.add_child(UI.label("选择一种玩法，坐下来玩一局。",19))
	col.add_child(UI.label("真实 3D 卡牌  ·  本地人机  ·  原创牌面",15,Color("98b4b4")))
	col.add_child(UI.button("21 点  /  八人环桌",func():get_tree().change_scene_to_file("res://scenes/blackjack_game.tscn"),true))
	col.add_child(UI.label("你 + 7 位 AI · 中央庄家 · 独立1000金币 · 桌面暗牌可查看",16))
	col.add_child(UI.button("彩序  /  UNO 风格",func():get_tree().change_scene_to_file("res://scenes/uno_game.tscn")))
	col.add_child(UI.label("2–8 人 · 自定义起牌与房规 · 每局剩牌计分",16))
	col.add_child(UI.button("卡牌实验室  /  通用 3D 模板",func():get_tree().change_scene_to_file("res://scenes/table_demo.tscn")))
	col.add_child(UI.label("金币仅供游戏，无充值、支付、兑换或真实价值。",14,Color("98b4b4")))
